name: Build and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  login_build_push_deploy:
    if: startsWith(github.event.head_commit.message, 'DEPLOY')
    name: Build & Deploy Update
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Build and push backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: mascit/ag:latest
      - name: restart backend deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.19.16
          command: rollout restart deployment/age-app
